### ISSUE TITLE
Release DEMO dataset on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [MozerWang/DEMO#1]
Hi @MozerWang,

Niels here from the open-source team at Hugging Face. I discovered your work through Hugging Face's daily papers as yours got featured: https://huggingface.co/papers/2412.04905.
The paper page lets people discuss about your paper and lets them find artifacts about it (your dataset for instance), you can also claim the paper as yours which will show up on your public profile at HF.

It would be great to host the DEMO dataset on HuggingFace Datasets. It will improve its discoverability and allow people to use the following simple code:

```python
from datasets import load_dataset
dataset = load_dataset("your-hf-org-or-username/DEMO")
```

Hosting the dataset on Hugging Face will provide better visibility and allow for easier discoverability. We can add tags to the dataset card to make it easier for people to find. We also support WebDataset, which is helpful for image/video datasets.

Are you interested in hosting your dataset on Hugging Face?  We can provide guidance on uploading if needed.

Kind regards,
Niels

**Comment by MozerWang** [comment]
Thanks for your advice. I will uploda DEMO dataset on Hugging Face.

**Comment by NielsRogge** [comment]
Thanks, could you keep this issue open so that we can track it?

**Comment by MozerWang** [comment]
Ok, sorry I've been busy recently. Would you like me to keep this issue open until I upload it to Huggingface?

**Comment by MozerWang** [comment]
Data have been uploaded to Huggingface! [[😊 Data](https://huggingface.co/iiiiwis/DEMO)]

**Comment by NielsRogge** [comment]
Thanks! Although for me it results in a 404

**Comment by MozerWang** [comment]
sorry for mistake：https://huggingface.co/datasets/iiiiwis/DEMO

**Comment by NielsRogge** [comment]
Thank you!
